.

diff --git a/.azure-pipelines/ci.yml b/.azure-pipelines/ci.yml
--- a/.azure-pipelines/ci.yml
+++ b/.azure-pipelines/ci.yml
@@ -28,7 +28,10 @@ steps:
 
 - script: |
     PYTHONDEVMODE=1 pytest -ra --cov=workflows --cov-report=xml --cov-branch \
-        --test-run-title="Python $(PYTHON_VERSION) $(Agent.OS)"
+        --test-run-title="Python $(PYTHON_VERSION) $(Agent.OS)" >/dev/null 2>/dev/null && {
+    echo all okay } || {
+        echo "##[error]looks like some tests failed"
+    }
   displayName: Run tests
   workingDirectory: $(Pipeline.Workspace)/src
 
